spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/luisoracle
    username: system
    password: Lf1291716
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true